### ISSUE TITLE
can you add some example how to use it ?

### ISSUE THREAD

**Issue by djsuszi** [EnergieID/FusionSolar#1]

**Comment by SirSiggi** [comment]
It seems as if this client is by no means complete. The only thing it can do - as far as I see it - is get daily data. But it is a good base for adding features. 

Here is what it can do:

```
#!/usr/bin/python3

import fusionsolar.client
import json
import pandas

cl = fusionsolar.client.Client("user", "password")
cl.login()
stations = cl.get_stations()
print(json.dumps(stations, indent=4, sort_keys=True))

kpi_day = cl.get_kpi_day("stationcode from get_stations", pandas.Timestamp.now())
print(json.dumps(kpi_day, indent=4, sort_keys=True))

```

All other API-methods are not implemented in this client.

**Comment by JrtPec** [comment]
demo notebook and readme were updated. Feel free to add more examples.
