### ISSUE TITLE
HTTPError: 403

### ISSUE THREAD

**Issue by BobKooistra** [EnergieID/FusionSolar#7]
L.s.,
Very irregular, but almost every day I get an HTTPError: 403 (Client Error: Forbidden for url: base..). So I don't always get this error, it also works fine on a regular basis. So completely unpredictable. Is there something to do about this??
See a bit of logging below.
Mrsgr, Bob.

*** BkHuaFuSo1 Proc _request: getStationList
Traceback (most recent call last):
  File "/home/pi/domoticz/BkMeiKade1/BkMeiKade1.py", line 154, in <module>
    sl = client.get_station_list()
  File "/home/pi/domoticz/BkMeiKade1/fusionsolar/client.py", line 199, in get_station_list
    return self._request("getStationList")
  File "/home/pi/domoticz/BkMeiKade1/fusionsolar/client.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/domoticz/BkMeiKade1/fusionsolar/client.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/domoticz/BkMeiKade1/fusionsolar/client.py", line 183, in _request
    self._validate_response(r)
  File "/home/pi/domoticz/BkMeiKade1/fusionsolar/client.py", line 146, in _validate_response
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://intl.fusionsolar.huawei.com/thirdData/getStationList

**Comment by vlad-sunvigo** [comment]
I have the same problem. There is probably an error in the token expiration logic. My solution for now is to log out using Postman as described in the API manual.

Maybe it would be good to have a logout method in this module. I could write it.

**Comment by vlad-sunvigo** [comment]
I created the pull request for the logout method.
https://github.com/EnergieID/FusionSolar/pull/8

**Comment by BobKooistra** [comment]
Hi Vlad-sunvigo,
Thanks for your reaction and the logout coding.
I’m still having the problem, so maybe this will help.
But.. how do I use this logout procedure?
Shouldn't the client.py code also be modified to use the logout in any way? 
Something like: class HTTPError401(HTTPError): xx but then for the 403 error? 
As you understand, I'm not really a coding specialist..
Hopefully you can help.
Regards, Bob

**Comment by BobKooistra** [comment]
For who is interested,
I made a bypass for the problem by doing the login multiple times after the 403 error with some wait time in between until the login succeeded. This succeeded almost every login attempt within max 3 retries (90%).
However, for some day’s now (2 weeks??) the login and “getstationlist” succeeds after 0 retries, so without any error (403) occurring. I don’t know what has changed, maybe Huawei made an adjustment, no idea. But the problem is gone, at least for me and hopefully for everyone.
Success, regards, Bob.
